# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'godott'

#google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Writings', path: 'menu/writings_menu', url: 'index.html'}
- {name: 'Photos', path: 'menu', url: 'photos.html'}

writings_menu:
- {name: 'chronological', path: 'menu/writings_menu', url: 'index.html'}
- {name: 'collections', path: 'menu/writings_menu', url: 'category.html'}

my_categories:
- {name: 'Quantum compilation', path: 'menu/writings_menu/category', url: 'qcompilation.html', image: 'qcompilation.jpg'}
- {name: 'Circuit QED', path: 'menu/writings_menu/category', url: 'cqed.html', image: 'qc.jpg'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/godott'}
- {icon: 'twitter', link: 'https://twitter.com/synisnot'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/yunong-shi-b0836a50/'}
- {icon: 'envelope', link: 'mailto:synisnot@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'related posts:'

post_date_prefix: 'Written on'
